# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5d5aceebcc6a61075388031c8ef7aaaed2e0ed8809d16d3173131664e2132fd7247d1c1b4f5c11c8341b4065faaf73adb10cf3cc4d4ba49a0625ae6e78d02b02

test:
  secret_key_base: f8c367acfce7002967b5442cdef9de5d7f60c0399a9db09b730d5d47c472a6c4e4c46f55e10a489e8009345f6f5e4321c845ac77594fc40638840090919b272c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
